theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman
#github:
#  is_project_page: false
github: is\_project\_page:false
title: "Dr. Sven Eggimann"
description: "[Contact](https://www.empa.ch/web/egsv)"
show_downloads: false
logo: "data/image_sven.jpeg"
minimal_mistakes_skin: "aqua" # default "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"