theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman
github:
  is_project_page: "false"
title: "Dr. Sven Eggimann"
description: "A short description of your site's purpose"
logo: "data/image_sven.jpeg"
show_downloads: "false"
minimal_mistakes_skin: "aqua" # default "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"