theme: jekyll-theme-minimal
#theme: jekyll-theme-cayman
#github:
#  is_project_page: false
github: is\_project\_page:false
title: "Dr. Sven Eggimann"
description: >
  sven.eggimann@empa.ch
  <br><br>
  <a href="https://www.empa.ch/web/egsv">Institutional Website</a>
  <br><br>
  <a href="https://scholar.google.ch/citations?user=t_s-r4UAAAAJ&hl=de">Google Scholar</a>
  <br><br>

show_downloads: false
logo: "data/image_sven.jpeg"
minimal_mistakes_skin: "aqua" # default "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"