theme: jekyll-theme-minimal
github: is\_project\_page:false
title: "Dr. Sven Eggimann"
description: "A short description of your site's purpose"
logo: "data/orcid.png"
show_downloads: "true"
minimal_mistakes_skin: "default" # default "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"